CREATE DATABASE WebServiceDb;

USE WebServiceDb;

CREATE TABLE Users (
	IdUser INT PRIMARY KEY AUTO_INCREMENT,
	Firstname VARCHAR(50) NOT NULL,
	Lastname VARCHAR(50) NOT NULL,
	Login VARCHAR(50) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	Salt CHAR(8) NOT NULL,
	Role ENUM('manager','developer') NOT NULL
	--,IdManager INT,
	--FOREIGN KEY (IdManager) REFERENCES users(IdUser)
);
	
CREATE TABLE Projects (
	IdProject INT PRIMARY KEY AUTO_INCREMENT,
	Label VARCHAR(50) NOT NULL
);
CREATE TABLE TimeSlots (
	IdSlot INT PRIMARY KEY AUTO_INCREMENT,
	HourCount INT NOT NULL,
	IdUser INT NOT NULL,
	IdProject INT NOT NULL,
	ReferredDate DATE NOT NULL,
	FOREIGN KEY (IdUser) REFERENCES users(id_user),
	FOREIGN KEY (IdProject) REFERENCES projects(IdProject)
);
